# Generated by Django 3.1.4 on 2020-12-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20201210_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
