# Generated by Django 3.1.4 on 2020-12-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_auto_20201211_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
