# Generated by Django 3.1.4 on 2020-12-15 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculator', '0008_auto_20201211_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbon_output', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usersresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='usersresponse',
            name='quiz_taker',
        ),
        migrations.RemoveField(
            model_name='usersresponse',
            name='response',
        ),
        migrations.DeleteModel(
            name='QuizTaker',
        ),
        migrations.DeleteModel(
            name='UsersResponse',
        ),
    ]
