# Generated by Django 3.1.4 on 2020-12-15 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_auto_20201215_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
